kind: pipeline
type: docker
name: test-memprof

steps:
  - name: test-memprof
    image: tezedge/tezedge-bpf-builder:latest
    privileged: true
    volumes:
      - name: kernel-debug
        path: /sys/kernel/debug
      - name: proc-dir
        path: /proc
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - apt-get install -y pkg-config
      - rustup install nightly-2021-03-23
      # docker client
      - curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-20.10.0.tgz
      - tar xzf docker-20.10.0.tgz --strip 1 -C /usr/local/bin docker/docker
      - rm docker-20.10.0.tgz
      # build memprof
      - cargo +nightly-2021-03-23 install bpf-linker --git https://github.com/tezedge/bpf-linker.git --branch main
      - cargo +nightly-2021-03-23 test --package tezedge-memprof --lib --release -- history::history history::tests
      - cargo +nightly-2021-03-23 build -p bpf-memprof --release
      - cargo +nightly-2021-03-23 build -p tezedge-memprof --tests --release
      # run tezedge-node in docker
      - docker stop tezedge_node || true
      - TEZEDGE_NODE_NAME=tezedge_node ./target/none/release/bpf-memprof-user &
      - docker run --rm -d --name tezedge_node tezedge/tezedge:latest-frame-pointers-enabled --network florencenet
      # do tests
      - URL=http://localhost:17832 cargo +nightly-2021-03-23 test -p tezedge-memprof --release -- positive compare --nocapture
      # stop the node
      - docker stop tezedge_node

volumes:
  - name: kernel-debug
    host:
      path: /sys/kernel/debug
  - name: proc-dir
    host:
      path: /proc
  - name: docker_sock
    host:
      path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: test-recorder

steps:
  - name: test-recorder
    image: tezedge/tezedge-bpf-builder:latest
    privileged: true
    volumes:
      - name: tezedge-shared-data
        path: /tmp/volume
      - name: kernel-debug
        path: /sys/kernel/debug
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - apt-get install -y pkg-config clang libev-dev
      - rustup install nightly-2021-08-04
      - rustup install stable
      # docker client
      - curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-20.10.0.tgz
      - tar xzf docker-20.10.0.tgz --strip 1 -C /usr/local/bin docker/docker
      - rm docker-20.10.0.tgz
      # build recorder
      - cargo +stable install bpf-linker --git https://github.com/tezedge/bpf-linker.git --branch main
      - cargo +stable install --path bpf-recorder
      - cargo +nightly-2021-08-04 build -p tezedge-recorder --tests --release
      # stop old node if any
      - docker stop tezedge_node || true
      # remove old debugger's db if any
      - rm -Rf /tmp/volume/tezedge_debugger || true
      # test
      - ./tezedge-recorder/test.sh
      # test with real node
      - ./target/none/release/tezedge-recorder --run-bpf & sleep 2
      # run tezedge-node in docker
      - docker run --rm -d --name tezedge_node -v /tmp/volume/tezedge:/tmp/tezedge tezedge/tezedge:latest-frame-pointers-enabled --network mainnet --p2p-port 29734
      # test p2p
      - DEBUGGER_URL="http://localhost:17732" cargo +nightly-2021-08-04 test -p tezedge-recorder --release -- wait --nocapture
      - DEBUGGER_URL="http://localhost:17732" cargo +nightly-2021-08-04 test -p tezedge-recorder --release -- p2p_limit p2p_cursor p2p_types_filter --nocapture
      # stop the node
      - docker stop tezedge_node

volumes:
  - name: tezedge-shared-data
    host:
      path: /tmp/volume
  - name: kernel-debug
    host:
      path: /sys/kernel/debug
  - name: docker_sock
    host:
      path: /var/run/docker.sock

---

kind: pipeline
name: docker-deploy-develop

steps:
  - name: build-tezedge-debugger-image  
    image: plugins/docker
    settings:
      repo: tezedge/tezedge-debugger
      tag: latest
      dockerfile: Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd
  - name: build-tezedge-memprof-image  
    image: plugins/docker
    settings:
      repo: tezedge/tezedge-memprof
      tag: latest
      dockerfile: Dockerfile.memprof
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

image_pull_secrets:
  - docker_pull_secret

depends_on:
  - test-memprof
  - test-recorder

trigger:
  branch: develop
  event: push

---

kind: pipeline
name: docker-deploy-release

steps:
  - name: build-tezedge-debugger-image
    image: plugins/docker
    settings:
      repo: tezedge/tezedge-debugger
      tags: 
        - ${DRONE_TAG}
        - latest-release
      dockerfile: Dockerfile
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd
  - name: build-tezedge-memprof-image  
    image: plugins/docker
    settings:
      repo: tezedge/tezedge-memprof
      tags: 
        - ${DRONE_TAG}
        - latest-release
      dockerfile: Dockerfile.memprof
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

image_pull_secrets:
  - docker_pull_secret

depends_on:
  - test-memprof
  - test-recorder

trigger:
  ref: refs/tags/**
  event: tag
