FROM ubuntu:18.04 as build-env

RUN DEBIAN_FRONTEND='noninteractive' apt-get update && apt-get install -y \
    curl g++ git libssl-dev pkg-config libelf-dev libsodium-dev make \
    libjemalloc-dev libffi-dev libffi6 libev-dev \
    lsb-release wget software-properties-common && \
    wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 11 && rm llvm.sh

ARG rust_toolchain="nightly-2020-12-31"
RUN curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain ${rust_toolchain} -y
ENV RUST_BACKTRACE=1
ENV SODIUM_USE_PKG_CONFIG=1
ENV OCAML_BUILD_CHAIN=remote

WORKDIR /home/appuser

ARG tezedge_git="https://github.com/tezedge/tezedge.git"
ARG tezedge_debugger_git="https://github.com/tezedge/tezedge-debugger.git"
ARG SOURCE_BRANCH="develop"

RUN cd /home/appuser && git clone ${tezedge_debugger_git} --branch ${SOURCE_BRANCH}
RUN cd /home/appuser/tezedge-debugger && \
    ${HOME}/.cargo/bin/cargo install bpf-linker --git https://github.com/tezedge/bpf-linker.git --branch main && \
    ${HOME}/.cargo/bin/cargo build -p bpf-memprof --release && \
    ${HOME}/.cargo/bin/cargo build -p tezedge-memprof --release

RUN cd /home/appuser && git clone ${tezedge_git} --branch ${SOURCE_BRANCH}
RUN cd /home/appuser/tezedge && \
    PATH=/usr/lib/llvm-11/bin:${PATH} RUSTFLAGS="-Cforce-frame-pointers=yes" ${HOME}/.cargo/bin/cargo build --release #5

FROM ubuntu:20.10

RUN DEBIAN_FRONTEND='noninteractive' apt-get update && apt-get install -y \
    libelf-dev libsodium-dev libev-dev
RUN mkdir -p /tmp/tezedge/light-node

COPY --from=build-env /home/appuser/tezedge/target/release/light-node /
COPY --from=build-env /home/appuser/tezedge/target/release/protocol-runner /
COPY --from=build-env /home/appuser/tezedge/target/release/sandbox /
COPY --from=build-env /home/appuser/tezedge/sandbox/artifacts/tezos-client /

COPY --from=build-env /home/appuser/tezedge/docker/distroless/tezedge.config /

COPY --from=build-env /usr/lib/x86_64-linux-gnu/libffi.so.6 /usr/lib/x86_64-linux-gnu/libffi.so.6
COPY --from=build-env /home/appuser/tezedge/tezos/sys/lib_tezos/artifacts/libtezos.so \
    /usr/lib/x86_64-linux-gnu/libtezos.so

COPY --from=build-env /home/appuser/tezedge/tezos/sys/lib_tezos/artifacts/sapling-spend.params /
COPY --from=build-env /home/appuser/tezedge/tezos/sys/lib_tezos/artifacts/sapling-output.params /

COPY --from=build-env /home/appuser/tezedge-debugger/target/none/release/bpf-memprof-user /
COPY --from=build-env /home/appuser/tezedge-debugger/target/none/release/tezedge-memprof /

RUN echo "#!/usr/bin/bash\n\
    /bpf-memprof-user & sleep 0.5\n\
    /tezedge-memprof & sleep 0.5\n\
    /light-node --config-file=/tezedge.config --p2p-port=9732 --rpc-port=18732 --websocket-address=0.0.0.0:4927 --init-sapling-spend-params-file=/sapling-spend.params --init-sapling-output-params-file=/sapling-output.params --network mainnet\n\
    " > run.sh && chmod +x run.sh

CMD ./run.sh
